Feature/86 dropdown to header
AlexNemtsev/it-cards pull request #103
Opened 2024-05-22 21:46 UTC by mabar84

Переделал UserMenu. Все же убрал LinkItem и сделал в DropdownItem + пробрасывание стилей из UserMenu.
Вылогинивание работает, но с 401. Еще сломался сторибук. Вопрос в чате Субботы задал.
Прошу посмотреть Layout, UserMenu, Dropdown

2024-05-23 09:46 UTC, AlexNemtsev requested changes

2024-05-23 09:46 UTC, AlexNemtsev commented on .storybook/decorators/ReduxDecorator.tsx
> +import { FC } from 'react';
Откатить

2024-05-23 09:46 UTC, AlexNemtsev commented on .storybook/decorators/RouterDecorator.tsx
> +import { FC } from 'react';
Тоже откатить

2024-05-23 09:46 UTC, AlexNemtsev commented on .storybook/preview.ts
> +import { Preview } from '@storybook/react';
И это откатить

2024-05-23 09:46 UTC, AlexNemtsev commented on package.json
> +    "async-mutex": "^0.5.0",
Что за либа чудесная?

2024-05-23 09:46 UTC, AlexNemtsev commented on src/shared/api/flashcards-base-query.ts
Что-то мне подсказывает, что сторибук сломался из-за этого

2024-05-23 09:46 UTC, AlexNemtsev commented on src/entities/auth/api/auth.ts
> +        // },
Удалить

2024-05-23 09:46 UTC, AlexNemtsev commented on src/entities/auth/api/auth.ts
В целом сомнительные правки по логинизации

2024-05-23 09:46 UTC, AlexNemtsev commented on src/shared/api/flashcardsApi.ts
> +  tagTypes: ['Decks', 'Me', 'Deck'],
Мне кажется, что тэги не должны быть здесь

2024-05-23 09:46 UTC, AlexNemtsev commented on src/shared/ui/Layout/UserMenu/UserMenu.tsx
> +        </button>
А вот тут я бы использовал типографику c тэгом a, поскольку после разлогина нужно сделать переадресацию на sign in

2024-05-23 09:46 UTC, AlexNemtsev commented on src/shared/ui/Layout/UserMenu/UserMenu.tsx
> +    }
try-catch можно убрать

2024-05-23 09:46 UTC, AlexNemtsev commented on src/pages/ProfilePage/ProfilePage.tsx
> +      errorNotification(error.data.message || 'Some error occurred');
try-catch убрать, добавить редирект

2024-05-23 19:43 UTC, mabar84 commented on .storybook/decorators/ReduxDecorator.tsx
> +import { FC } from 'react';
исправил, но теперь у меня TS6133: 'React' is declared but its value is never read.

2024-05-23 19:43 UTC, mabar84 commented on .storybook/decorators/RouterDecorator.tsx
> +import { FC } from 'react';
+

2024-05-23 19:56 UTC, mabar84 commented on .storybook/preview.ts
> +import { Preview } from '@storybook/react';
+

2024-05-23 19:57 UTC, mabar84 commented on package.json
> +    "async-mutex": "^0.5.0",
авада-кедавра

2024-05-23 19:57 UTC, mabar84 commented on src/shared/api/flashcards-base-query.ts
да ты шаришь :)

2024-05-23 19:58 UTC, mabar84 commented on src/entities/auth/api/auth.ts
> +        // },
+

2024-05-23 19:58 UTC, mabar84 commented on src/entities/auth/api/auth.ts
+

2024-05-23 19:59 UTC, mabar84 commented on src/shared/api/flashcardsApi.ts
> +  tagTypes: ['Decks', 'Me', 'Deck'],
пока побудут

2024-05-23 20:54 UTC, mabar84 commented on src/pages/ProfilePage/ProfilePage.tsx
> +      errorNotification(error.data.message || 'Some error occurred');
тянул error, isError. типизация непонятная. т.е. не смог нормально вытянуть сообщение об ошибке из error. Редирект добавил, это убрало мигание на основную страницу при вылогинивании через ProfileInformation

2024-05-30 09:55 UTC, AlexNemtsev requested changes

2024-05-30 09:55 UTC, AlexNemtsev commented on .storybook/decorators/index.ts
Откатить

2024-05-30 09:56 UTC, AlexNemtsev commented on package.json
> +    "async-mutex": "^0.5.0",
тебе сделали экспелиармус, попробуй ещё раз

2024-05-30 11:29 UTC, mabar84 commented on package.json
> +    "async-mutex": "^0.5.0",
видимо, из-за нескольких доливов ветки логин в девелоп, а потом из девелоп в хеадер. короче, все комменты заново перепроверю

2024-05-30 18:18 UTC, mabar84 commented on .storybook/preview.ts
> +import { Preview } from '@storybook/react';
нужна пояснительная бригада. Если import { Preview } from '@storybook/react'; удаляю, то const preview: Preview = { краснеет. К тому же этот импорт в ветке develop есть

2024-05-30 18:19 UTC, mabar84 commented on package.json
> +    "async-mutex": "^0.5.0",
надеюсь, pnpm remove async-mutex сработает

2024-05-30 18:21 UTC, mabar84 commented on .storybook/decorators/index.ts
скопипастил с девелоп

2024-05-30 18:32 UTC, mabar84 commented on src/components/auth/SignUpForm/SignUpForm.stories.tsx
> +        {data?.email} {data?.password}
+

2024-05-30 20:18 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +  setAvatar: (avatar: object) => void;
поставил unknown

2024-05-30 20:21 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +  const { avatar = unknownAvatar, email, logout, name = '', onSubmit, setAvatar } = props;
+

2024-05-30 20:23 UTC, mabar84 commented on src/pages/ProfilePage/ProfilePage.tsx
> +  const setAvatarHandler = (avatar: object) => {
+

2024-05-30 20:23 UTC, mabar84 commented on src/shared/ui/Layout/UserMenu/UserMenu.tsx
> +  // };
+

2024-05-30 20:25 UTC, mabar84 commented on src/entities/auth/api/auth.ts
> +          body: args,
+

2024-05-30 20:34 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
>      }
Имеется в виду логика, которая сейчас на уровень выше в ProfilePage? 
const setAvatarHandler = (avatar: unknown) => {
    updateUserData(avatar);
  };
Просто старался делать однообразно со всем страничками, чтобы отступы и взаимодействие с сервером было в Page. Разве что тут с именами нестыковка. В макете Edit Profilt -> Personal Information, поэтому неплохо было бы решить, как назвать (ProfilePage->ProfileForm, например)

2024-05-30 20:38 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.stories.tsx
> +      //@ts-ignore
Вообще если в исходной компоненте будет any, то тут заглушка не понадобится. Но там было object, а сейчас unknown. Т.к. компонент первичен, то костылил в истории. Вообще вроде просится только примитивы показывать.  Но если показывать эту историю, то не смог без этого костыля выкрутиться. В компоненту аватар приходит с сервера. В истории - локальный файл. Новая аватарка летит на сервер, а тут использовался useState. Когда появилась FormData, появилась и заглушка ts-ignore

2024-05-31 10:01 UTC, AlexNemtsev approved these changes

2024-05-31 10:01 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
>      }
Насчёт логики окей, название пока такое оставим

2024-05-31 10:02 UTC, AlexNemtsev commented on .storybook/preview.ts
> +import { Preview } from '@storybook/react';
Таки откатил)

2024-06-04 07:12 UTC, AlexNemtsev requested changes

2024-06-04 07:12 UTC, AlexNemtsev commented on .storybook/preview.ts
Откатить

2024-06-04 07:12 UTC, AlexNemtsev commented on package.json
Тоже откатить

2024-06-04 07:12 UTC, AlexNemtsev commented on public/mockServiceWorker.js
Откатить

2024-06-04 09:35 UTC, AlexNemtsev approved these changes

2024-06-04 09:35 UTC, merged