Feature/84 add decks page
AlexNemtsev/it-cards pull request #106
Opened 2024-05-27 12:21 UTC by EvgenyStrunevsky

2024-05-28 11:13 UTC, AlexNemtsev requested changes

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +      </div>
Вынеси в отдельный виджет src/widgets/decks/DecksFilters.tsx

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +const VALUES = ['10', '20', '30', '50', '100'];
А что за VALUES?

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +}
Вынеси в shared/lib, убери undefined, переделай в стрелочную функцию

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +        searchParams.get('range')?.split(',').map(Number)[1] || minMaxCards?.max || 0,
Что-то в глазах двоится)))

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +  const range: [number, number] = searchParams.has('range')
проверка has избыточна

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.tsx
> +    : [minMaxCards?.min || 0, minMaxCards?.max || 0];
повторяет кусок выше

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/SignUpPage/SignUpPage.tsx
Откатить

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/ui/NewDeckTitle.tsx
Избыточный файл

2024-05-28 11:13 UTC, AlexNemtsev commented on src/pages/DecksPage/ui/OpenNewDeckModalButton.tsx
Избыточный файл

2024-05-29 11:00 UTC, EvgenyStrunevsky commented on src/components/auth/signUpForm/SignUpForm.tsx
+

2024-05-29 19:26 UTC, EvgenyStrunevsky commented on src/app/router/router.tsx
> +    children: [{ element: <DecksPage />, path: Routes.MAIN }],
+

2024-05-29 19:42 UTC, EvgenyStrunevsky commented on src/entities/auth/api/auth.ts
+

2024-05-29 19:43 UTC, EvgenyStrunevsky commented on src/pages/SignUpPage/SignUpPage.tsx
+

2024-05-30 08:48 UTC, EvgenyStrunevsky commented on pnpm-lock.yaml
+

2024-05-30 09:17 UTC, EvgenyStrunevsky commented on src/entities/deck/api/api.ts
> +};
+

2024-05-30 10:06 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +}
+

2024-05-30 10:28 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +        searchParams.get('range')?.split(',').map(Number)[1] || minMaxCards?.max || 0,
+

2024-05-30 10:29 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +  const range: [number, number] = searchParams.has('range')
+

2024-05-30 10:31 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +    : [minMaxCards?.min || 0, minMaxCards?.max || 0];
+

2024-06-03 09:18 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +  }
+

2024-06-03 09:26 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/DecksPage.tsx
> +const VALUES = ['10', '20', '30', '50', '100'];
+

2024-06-05 15:17 UTC, closed without merging