Feature/layout to app
AlexNemtsev/it-cards pull request #120
Opened 2024-06-12 12:15 UTC by mabar84

2024-06-14 08:51 UTC, AlexNemtsev requested changes

2024-06-14 08:51 UTC, AlexNemtsev commented on src/features/UserMenu/Trigger/index.ts
Переименуй лучше в DropdownTrigger

2024-06-18 09:46 UTC, AlexNemtsev commented on src/shared/ui/Dropdown/Dropdown.module.scss
> +}
А зачем оно надо?

2024-06-18 09:52 UTC, mabar84 commented on src/shared/ui/Dropdown/Dropdown.module.scss
> +}
потому что Дропдаун-айтемы сделаны универсальные: иногда только текст, иногда текст с иконкой. И если текст с иконкой, то без display: flex выглядит некрасиво.

2024-06-18 09:56 UTC, AlexNemtsev commented on src/shared/ui/Dropdown/Dropdown.module.scss
> +}
В таком случае лучше вынести этот класс в другой файл, можно, думаю, даже не в модуль, и импортировать этот класс в истории

2024-06-18 10:00 UTC, mabar84 commented on src/shared/ui/Dropdown/Dropdown.module.scss
> +}
А куда этот файл положить? Рядом с историей? Или может вообще в файле с историей объект со стилями сделать и его в style в тег добавить?

2024-06-19 10:03 UTC, AlexNemtsev approved these changes

2024-06-19 10:03 UTC, merged