Refactoring/127 decks page decomposition
AlexNemtsev/it-cards pull request #136
Opened 2024-06-21 14:30 UTC by EvgenyStrunevsky

2024-06-26 14:44 UTC, AlexNemtsev requested changes

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/consts/consts.ts
> +};
Что тип делает в константах? + его лучше через Record написать

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/consts/consts.ts
файл лучше положить в src/pages/DecksPage/lib/constants.ts

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/useQueryParam.ts
> +): [T | null, (value: T | null) => void] {
Возьмёшь потом у Миши Nullable

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/useQueryParam.ts
> +    if (value === undefined || value === null || value === '') {
Есть более простой способ задать это условие

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/useQueryParam.ts
> +export function useQueryParam<T extends boolean | number | string>(
мы используем стрелочные функции

2024-06-26 14:44 UTC, AlexNemtsev commented on src/pages/DecksPage/useQueryParam.ts
> +}
Такая типизация не годится – на выходе у тебя может быть только string | number | boolean | null – и где-то этот union я уже видел

2024-06-26 14:44 UTC, AlexNemtsev commented on src/shared/ui/DebouncedInput/DebouncedInput.tsx
А нужна ли эта обёртка с новым useDebounce?

2024-06-26 14:44 UTC, AlexNemtsev commented on src/widgets/Deck/DecksHeader/DecksHeader.tsx
я бы не стал выносить в виджеты, а просто положил в подпапку ui к странице

2024-06-26 14:44 UTC, AlexNemtsev commented on src/widgets/decks/DecksTable/DecksTable.tsx
> +} from '@/pages/DecksPage/consts';
Виджет не может брать данные с уровня страницы

2024-06-27 08:21 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/consts/consts.ts
> +};
+

2024-06-27 08:22 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useQueryParam.ts
> +): [T | null, (value: T | null) => void] {
Файл удален

2024-06-27 08:22 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useQueryParam.ts
> +    if (value === undefined || value === null || value === '') {
Файл удален

2024-06-27 08:22 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useQueryParam.ts
> +export function useQueryParam<T extends boolean | number | string>(
Файл удален

2024-06-27 08:22 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useQueryParam.ts
> +}
Файл удален

2024-06-27 08:24 UTC, EvgenyStrunevsky commented on src/widgets/Deck/DecksHeader/DecksHeader.tsx
+

2024-06-27 09:06 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/consts/consts.ts
+

2024-06-28 07:39 UTC, EvgenyStrunevsky commented on src/shared/ui/DebouncedInput/DebouncedInput.tsx
Нужна со старым)

2024-06-28 10:07 UTC, AlexNemtsev requested changes

2024-06-28 10:07 UTC, AlexNemtsev commented on src/shared/ui/DebouncedInput/DebouncedInput.tsx
> +  }, [value]);
Для чего тут useEffect?

2024-06-28 10:07 UTC, AlexNemtsev commented on src/widgets/Deck/CardsTable/CardsTable.tsx
> +    question: question,
откатить

2024-06-28 10:07 UTC, AlexNemtsev commented on src/shared/constants/tabSwitcherStates.ts
Перемести лучше в decks filters

2024-06-28 12:23 UTC, EvgenyStrunevsky commented on src/widgets/Deck/CardsTable/CardsTable.tsx
> +    question: question,
+

2024-06-28 12:36 UTC, EvgenyStrunevsky commented on src/shared/constants/tabSwitcherStates.ts
+

2024-06-28 12:36 UTC, EvgenyStrunevsky commented on src/shared/ui/DebouncedInput/DebouncedInput.tsx
> +  }, [value]);
решили оставить пока

2024-07-01 08:07 UTC, AlexNemtsev approved these changes

2024-07-01 08:08 UTC, merged