Feature/modal add new card
AlexNemtsev/it-cards pull request #137
Opened 2024-06-23 12:53 UTC by mabar84

2024-06-24 09:23 UTC, AlexNemtsev requested changes

2024-06-24 09:23 UTC, AlexNemtsev commented on src/entities/card/api/cardApi.ts
> +          formData.append('question', question);
Что-то мне подсказывает, что этим делом должна заниматься форма

2024-06-24 09:23 UTC, AlexNemtsev commented on src/entities/card/api/types.ts
> +export type CreateCardRequest = {
CreateCardQueryArgs

2024-06-24 09:23 UTC, AlexNemtsev commented on src/entities/card/api/types.ts
> +export type Nullable<T> = T | null;
тип избыточен

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/DeckPage.tsx
> +    formData.append('question', question);
А вот он и код из rtk

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/DeckPage.tsx
> +          <AddNewCardModal onCreateCard={onCreateCard} />
А этот пропс можно и не делать, достаточно логику выше разместить с модалкой

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
Модалку я бы поместил в features

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        {/*  />*/}
убрать

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        {/*{answerImg && (*/}
убрать

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        </Button>
Напрашивается отдельный компонент – это ещё встречается в аватаре

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/EditCardModal/EditCardModal.tsx
> +        {/*)}*/}
убрать

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/EditCardModal/EditCardModal.tsx
> +  };
Тоже убрать

2024-06-24 09:23 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/EditCardModal/EditCardModal.tsx
> +  // const [questionImg, setQuestionImg] = useState<File | null | string>(card.questionImg);
убрать

2024-06-24 10:58 UTC, mabar84 commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        {/*  />*/}
+

2024-06-24 11:05 UTC, mabar84 commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        </Button>
Да, тут подойдет отдельный компонент именно для модалок (добавить, редактировать карту/колоду). У данной Label стили от Button. В аватаре совсем другая, может и не стоит ее трогать?

2024-06-25 10:13 UTC, AlexNemtsev requested changes

2024-06-25 10:13 UTC, AlexNemtsev commented on src/features/AddNewCardModal/useAddNewCardModal.ts
> +  const [questionImg, setQuestionImg] = useState<File | null>(null);
А тут можно использовать Nullable<T>

2024-06-25 10:13 UTC, AlexNemtsev commented on src/features/EditCardModal/EditCardModal.tsx
> +export const EditCardModal = ({ card }: Props) => {
Так дестуктуризировать мы не договаривались

2024-06-25 10:13 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/UploadButton/UploadButton.tsx
А в shared нельзя положить, чтобы использовать в Avatar?

2024-06-25 10:13 UTC, AlexNemtsev commented on src/shared/ui/Modal/Modal.tsx
> +  const { children, className = '', title, trigger, ...restProps } = props;
className, вроде, можно оставлять без инициализации

2024-06-25 10:14 UTC, AlexNemtsev commented on src/pages/DeckPage/ui/AddNewCardModal/AddNewCardModal.tsx
> +        </Button>
ок

2024-06-26 14:12 UTC, AlexNemtsev requested changes

2024-06-26 14:12 UTC, AlexNemtsev commented on src/entities/card/api/types.ts
Типы лучше вынести из api

2024-06-27 08:02 UTC, AlexNemtsev approved these changes

2024-06-27 08:03 UTC, merged