Feature/132 add new deck send request
AlexNemtsev/it-cards pull request #146
Opened 2024-07-02 09:29 UTC by EvgenyStrunevsky

2024-07-03 10:38 UTC, AlexNemtsev requested changes

2024-07-03 10:38 UTC, AlexNemtsev commented on src/entities/deck/api/types.ts
> +  cover?: File | null;
null убрать

2024-07-03 10:38 UTC, AlexNemtsev commented on src/entities/card/lib/convertNewCardDataToFormData.ts
> +import { AddNewCardFormValues } from '@/features/AddNewCardModal/NewCardForm/NewCardForm';
entity не может использовать feature

2024-07-03 10:38 UTC, AlexNemtsev commented on src/entities/deck/api/types.ts
> +export type CreateDeck = {
лучше назвать Deck

2024-07-03 10:38 UTC, AlexNemtsev commented on src/entities/deck/api/types.ts
> +};
Возможно эти типы уже есть в shared/api/schema

2024-07-03 10:38 UTC, AlexNemtsev commented on src/entities/deck/lib/convertDataToFormData.ts
> +import { NewDeckFormValues } from '@/widgets/decks/AddNewDeckModal/NewDeckForm/NewDeckForm';
entity не может использовать widget

2024-07-03 10:38 UTC, AlexNemtsev commented on src/shared/ui/UploadButtonWithController/UploadButtonWithController.tsx
> +import { UploadButton, UploadButtonProps } from '@/pages/DeckPage/ui/UploadButton/UploadButton';
Опять таки shared не может использовать pages

2024-07-03 10:46 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +  cover?: File | null;
+

2024-07-03 10:54 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +export type CreateDeck = {
уже есть, и они отличаются одним полем

2024-07-03 12:17 UTC, EvgenyStrunevsky commented on src/entities/card/lib/convertNewCardDataToFormData.ts
> +import { AddNewCardFormValues } from '@/features/AddNewCardModal/NewCardForm/NewCardForm';
+

2024-07-03 12:18 UTC, EvgenyStrunevsky commented on src/entities/deck/lib/convertDataToFormData.ts
> +import { NewDeckFormValues } from '@/widgets/decks/AddNewDeckModal/NewDeckForm/NewDeckForm';
+

2024-07-03 14:06 UTC, EvgenyStrunevsky commented on src/shared/ui/UploadButtonWithController/UploadButtonWithController.tsx
> +import { UploadButton, UploadButtonProps } from '@/pages/DeckPage/ui/UploadButton/UploadButton';
+

2024-07-04 08:26 UTC, AlexNemtsev requested changes

2024-07-04 08:26 UTC, AlexNemtsev commented on src/entities/deck/api/types.ts
> +export type CreateDeck = {
А по-моему, они одинаковы, и лучше использовать то, что есть

2024-07-04 09:05 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +export type CreateDeck = {
Саша, ты прав))) Большое спасибо) У меня в типизации была ошибка. Лишнее поле в Deck. Убрал CreateDeck

2024-07-04 09:51 UTC, AlexNemtsev approved these changes

2024-07-04 09:51 UTC, merged