Feature/143 edit delete deck
AlexNemtsev/it-cards pull request #150
Opened 2024-07-09 07:12 UTC by EvgenyStrunevsky

2024-07-10 11:19 UTC, AlexNemtsev requested changes

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/Deck/CardHeader/CardHeader.tsx
> +  const isYourDeck = meData?.id === deck?.userId;
Лучше назвать currentUserDeck

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/Deck/CardsTable/model/constants.ts
> +export const VARIANTS_ITEMS_PER_PAGE = ['10', '20', '30', '50', '100'];
ITEMS_PER_PAGE_VARIANTS

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/Deck/CardsTable/ui/ToolsButton/ToolsButton.tsx
> +type Props = { children: ReactNode } & ComponentPropsWithoutRef<'button'>;
У button и так есть типизация children

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/decks/DeleteDeckModal/ui/DeleteDeckTitle.tsx
> +  return <div>Are you sure you want to delete the deck?</div>;
div замени на p

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/decks/EditDeckModal/EditDeckForm/EditDeckForm.tsx
> +  cover: z.any().optional(),
опять any

2024-07-10 11:19 UTC, AlexNemtsev commented on src/widgets/Deck/CardsTable/CardsTable.tsx
> +  const isYourDeck = meData?.id === deck?.userId;
currentUserDeck

2024-07-10 13:23 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +export type createDecksArgs = { file?: any; pack: string; private?: boolean | undefined };
+

2024-07-10 13:23 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +  data: { file?: any; pack: string; private?: boolean | undefined };
+

2024-07-10 13:23 UTC, EvgenyStrunevsky commented on src/features/EditCardModal/EditCardForm/EditCardForm.tsx
> +  answerImg: z.any().optional(),
+

2024-07-10 13:27 UTC, EvgenyStrunevsky commented on src/widgets/Deck/CardsTable/model/constants.ts
> +export const VARIANTS_ITEMS_PER_PAGE = ['10', '20', '30', '50', '100'];
+

2024-07-10 13:30 UTC, EvgenyStrunevsky commented on src/widgets/Deck/CardsTable/ui/ToolsButton/ToolsButton.tsx
> +type Props = { children: ReactNode } & ComponentPropsWithoutRef<'button'>;
+

2024-07-10 13:49 UTC, EvgenyStrunevsky commented on src/widgets/decks/DeleteDeckModal/ui/DeleteDeckTitle.tsx
> +  return <div>Are you sure you want to delete the deck?</div>;
+

2024-07-10 13:50 UTC, EvgenyStrunevsky commented on src/widgets/decks/EditDeckModal/EditDeckForm/EditDeckForm.tsx
> +  cover: z.any().optional(),
+

2024-07-10 13:57 UTC, EvgenyStrunevsky commented on src/entities/deck/api/types.ts
> +};
+

2024-07-11 13:37 UTC, AlexNemtsev requested changes

2024-07-11 13:37 UTC, AlexNemtsev commented on src/shared/ui/UploadButton/UploadButton.tsx
А есть вообще смысл в этой кнопке без контролера? Мб функциональность контролера здесь разместить?

2024-07-11 13:37 UTC, AlexNemtsev commented on src/features/EditCardModal/EditCardForm/EditCardForm.tsx
> +  questionImg: z.any().optional(),
Тоже any

2024-07-11 13:37 UTC, AlexNemtsev commented on src/widgets/Deck/CardHeader/CardHeader.tsx
> +      {deck?.cover && <img alt="cover" className={s.cover} src={deck.cover} />}
проверку deck !== null лучше вынести перед фрагментом, тогда у тебя будет 1 проверка вместо 2

2024-07-11 13:37 UTC, AlexNemtsev commented on src/widgets/decks/DecksTable/model/constants.ts
У тебя этот файл дублируется

2024-07-12 08:49 UTC, EvgenyStrunevsky commented on src/shared/ui/UploadButton/UploadButton.tsx
Универсальность, потенциально проще заменить одну библиотеку обработки форм на другую. Поменяется только обертка.

2024-07-12 08:50 UTC, EvgenyStrunevsky commented on src/widgets/Deck/CardHeader/CardHeader.tsx
> +      {deck?.cover && <img alt="cover" className={s.cover} src={deck.cover} />}
Нашел только сомнительные способ, добавить еще один фрагмент)))

2024-07-12 08:50 UTC, EvgenyStrunevsky commented on src/widgets/decks/DecksTable/model/constants.ts
+

2024-07-12 10:00 UTC, AlexNemtsev approved these changes

2024-07-12 10:04 UTC, AlexNemtsev requested changes

2024-07-12 10:04 UTC, AlexNemtsev commented on src/widgets/Deck/CardHeader/CardHeader.tsx
> +    <>
Фрагмент лишний

2024-07-12 11:17 UTC, EvgenyStrunevsky commented on src/widgets/Deck/CardHeader/CardHeader.tsx
> +    <>
Без него конструкция не работает

2024-07-15 07:50 UTC, AlexNemtsev approved these changes

2024-07-15 07:51 UTC, merged