Feature/155 responsive decks page
AlexNemtsev/it-cards pull request #157
Opened 2024-08-08 10:23 UTC by EvgenyStrunevsky

2024-08-09 09:13 UTC, AlexNemtsev requested changes

2024-08-09 09:13 UTC, AlexNemtsev commented on src/app/styles/_boilerplate.scss
> +  }
Вопрос: есть ли принципилальная разница в паддингах с разницей в 1 пиксель? Мне кажется, что можно обойтись одним.
По наименованию: лучше называть laptop-padding

2024-08-09 09:13 UTC, AlexNemtsev commented on src/pages/DecksPage/DecksPage.module.scss
> +  // gap: 20px;
Убрать

2024-08-09 09:13 UTC, AlexNemtsev commented on src/pages/DecksPage/useDecksSearchParams.ts
> +  const getMobileOrderDecksBy = (value: string) => {
Непонятное название

2024-08-09 09:13 UTC, AlexNemtsev commented on src/shared/ui/Slider/Slider.module.scss
> +  min-width: 251px;
переделай на 250 лучше

2024-08-09 09:13 UTC, AlexNemtsev commented on src/widgets/decks/AddNewDeckModal/AddNewDeckModal.tsx
> +import { OpenNewDeckModalButton } from './ui/OpenNewDeckModalButton/OpenNewDeckModalButton';
откатить

2024-08-09 09:13 UTC, AlexNemtsev commented on vite.config.ts.timestamp-1722328693924-fa9171ee5e877.mjs
Это что за чудо-юдо? Удалить

2024-08-09 09:18 UTC, EvgenyStrunevsky commented on src/app/styles/_boilerplate.scss
> +  }
Это переменная еще и для десктопа

2024-08-09 09:19 UTC, EvgenyStrunevsky commented on src/app/styles/_boilerplate.scss
> +  }
+

2024-08-09 09:21 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useDecksSearchParams.ts
> +  const getMobileOrderDecksBy = (value: string) => {
+

2024-08-09 09:21 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useDecksSearchParams.ts
> +  const getMobileOrderDecksBy = (value: string) => {
+

2024-08-09 09:23 UTC, EvgenyStrunevsky commented on vite.config.ts.timestamp-1722328693924-fa9171ee5e877.mjs
это фальшивка сфабрикованная в Польше)))))

2024-08-09 09:25 UTC, EvgenyStrunevsky commented on src/shared/ui/Slider/Slider.module.scss
> +  min-width: 251px;
+

2024-08-09 10:19 UTC, AlexNemtsev requested changes

2024-08-09 10:19 UTC, AlexNemtsev commented on src/pages/DecksPage/useDecksSearchParams.ts
> +  const getOrderDecksByForTablet = (value: string) => {
setSortDecksBy – так будет лучше

2024-08-09 12:34 UTC, EvgenyStrunevsky commented on src/pages/DecksPage/useDecksSearchParams.ts
> +  const getOrderDecksByForTablet = (value: string) => {
+

2024-08-12 11:31 UTC, AlexNemtsev approved these changes

2024-08-12 11:31 UTC, merged