Feature/7 add checkbox component
AlexNemtsev/it-cards pull request #19
Opened 2024-03-05 16:28 UTC by mabar84

https://prnt.sc/-TXxx6c4CTLk

![Screenshot_3](https://github.com/AlexNemtsev/it-cards/assets/80951401/80324e84-9ced-44dc-9b65-a0457e64d8de)

На скриншоте показана потенциальная проблема при близко расположенном инпуте. Решается добавлением паддинга красной обертке. Но это увеличивает высоту, поэтому пока не добавлял

2024-03-06 09:19 UTC, AlexNemtsev requested changes

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +            </svg>
Вынеси в отдельный компонент

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +import { ComponentPropsWithoutRef, ReactNode, useState } from 'react';
Переименуй файлы – файлы компонентов должны начинаться с заглавной буквы

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +} & ComponentPropsWithoutRef<'form'>;
Почему form?

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +  isDisabled?: boolean;
в input эти props checked и disabled соответственно

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +  const [checked, setChecked] = useState(isChecked);
А зачем тут state?

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +  };
Получается, что компонент неконтролируемый?

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +          className={`${s.CheckboxRoot} ${isDisabled && s.disabled} ${checked && s.checked}`}
Вынеси в константу

2024-03-06 09:19 UTC, AlexNemtsev commented on src/components/ui/checkbox/checkbox.tsx
> +        </label>
В данный момент id чекбокса – хардкод, представь, что будет, когда на форме будет несколько чекбоксов

2024-03-07 08:12 UTC, AlexNemtsev requested changes

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.tsx
> +        className={`${s.CheckboxRoot}`}
А если мы захотим стилизовать чекбокс стилями из вне?

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.tsx
> +          <CheckedMark />
А если нужно будет передать в чекбокс крестик?

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckboxWithText.tsx
> +    <div className={s.CheckboxWrapper}>
Такой же вопрос к div

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckboxWithText.tsx
> +  text?: string;
Что если мы захотим передавать сюда не строку, а компонент типографики?

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckboxWithText.tsx
> +        </Checkbox.Root>
Дублирует код компонента Checkbox

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.module.scss
> +  }
Эту стилизацию нужно вынести к компоненту с иконкой

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.module.scss
> +  [data-state='checked'] {
Замени использование атрибута на соответствующий класс

2024-03-07 08:12 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckboxWithText.module.scss
Из-за то, что ты не переиспользуешь уже готовый Checkbox, у тебя ещё повторяются стили.

2024-03-09 10:24 UTC, AlexNemtsev requested changes

2024-03-09 10:24 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.stories.ts
> +const a = () => {
Что такое a, а?

2024-03-09 10:24 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.tsx
> +      {children}
Какие children предполагается принимать в checkbox?

2024-03-09 10:24 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckedCross.tsx
> +    </svg>
Вынеси в assets

2024-03-09 10:24 UTC, AlexNemtsev commented on src/components/ui/checkbox/CheckedMark.tsx
> +    </svg>
Это тоже в assets

2024-03-11 08:09 UTC, AlexNemtsev requested changes

2024-03-11 08:09 UTC, AlexNemtsev commented on src/components/ui/checkbox/Checkbox.module.scss
> +}
Может случиться утечка стилей, нужно проверить

2024-03-11 18:11 UTC, mabar84 commented on src/components/ui/checkbox/Checkbox.module.scss
> +}
Заменил на такое: CheckboxRoot {   all: unset;... }. Проверил. Против button {background: red} в общем index.scss защищает. Против button {background: red !important} - нет. Но !important в проекте надеюсь не увидеть

2024-03-11 18:12 UTC, mabar84 commented on package.json
> +    "@radix-ui/react-icons": "^1.3.0",
Не трогал, т.к. 1) файл общий 2) не понял, почему @radix-ui/react-checkbox": "^1.0.4 не надо

2024-03-11 18:15 UTC, AlexNemtsev commented on package.json
> +    "@radix-ui/react-icons": "^1.3.0",
Ты же берешь галочку из макета, а не из Radix

2024-03-11 19:03 UTC, AlexNemtsev requested changes

2024-03-11 19:03 UTC, AlexNemtsev commented on src/components/ui/Checkbox/Checkbox.stories.tsx
> +export const ExampleUnChecked: Story = {
CheckboxUnchecked, иначе storybook разбивает на три слова

2024-03-11 19:03 UTC, AlexNemtsev commented on src/components/ui/Checkbox/Checkbox.stories.tsx
> +export const ExampleCheckedMark: Story = {
CheckboxChecked

2024-03-11 19:03 UTC, AlexNemtsev commented on src/components/ui/Checkbox/Checkbox.stories.tsx
> +export const ExampleDisabled: Story = {
CheckboxDisabled

2024-03-11 19:03 UTC, AlexNemtsev commented on src/components/ui/Checkbox/Checkbox.tsx
> +  id?: string;
Перепроверь, будет ли всё ок работать, если ты уберёшь id из типов – по идее он должен и так присутствовать у Checkbox.Root

2024-03-11 19:03 UTC, AlexNemtsev commented on src/components/ui/Checkbox/Checkbox.tsx
> +export const CheckboxRadix = (props: Props) => {
Переименуй в Checkbox

2024-03-11 20:12 UTC, mabar84 commented on src/components/ui/Checkbox/Checkbox.module.scss
> +  }
Оказалось, что эти строки лишние. Размер задан в теле SVG, заливка не указана. Просто убрал, внешний вид и поведение не изменились

2024-03-12 10:11 UTC, mabar84 commented on src/components/ui/Checkbox/Checkbox.tsx
> +  id?: string;
Проверил. Убрал, работает

2024-03-12 10:13 UTC, mabar84 commented on src/components/ui/Checkbox/Checkbox.tsx
> +export const CheckboxRadix = (props: Props) => {
Конфликтует с Checkbox.Root и т.д.

2024-03-12 12:51 UTC, AlexNemtsev approved these changes
Так держать!

2024-03-12 13:07 UTC, merged