feature/8_add_input_component
AlexNemtsev/it-cards pull request #29
Opened 2024-03-14 09:44 UTC by EvgenyStrunevsky

I added input component

2024-03-14 19:31 UTC, mabar84 commented on src/components/ui/Input/index.ts
export { Card } from './Card'; - вместо * имя компоненты

2024-03-14 19:49 UTC, mabar84 reviewed
Что бросилось в глаза, указал. Думаю, по качеству кода Саша добавит

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/Search/search-outline.svg
Видимо, файл оставлен случайно, а его содержимое уже в Search.tsx

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/Search/index.ts
> +export * from './Search';
{Search} вместо *

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/Search/Search.tsx
> +        <clipPath id="clip0_5661_1973">
тут много лишнего. но особенно не нравится id

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/Search/Search.module.scss
> +  // margin: 10px;
удивлен, что получилось запушить закомментированные стили

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/EyeOff/index.ts
> +export * from './EyeOff';
везде имя компонента вместо *, больше не буду указывать. И так понятно

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/EyeOff/eye-off-outline.svg
везде свг-шки уже лишние

2024-03-14 19:49 UTC, mabar84 commented on src/assets/icons/EyeOff/EyeOff.tsx
> +      className={clsx(s.eye, disabled && s.disabled)}
Просится до return 
const classNames = clsx(s.eye, { [s.disabled]: disabled});
а в стр14:   className={classNames}

2024-03-15 09:22 UTC, AlexNemtsev requested changes

2024-03-15 09:22 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        </label>
Замени на Typography

2024-03-15 09:22 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +      {error && <div className={clsx(s.error)}>{error}</div>}
Тоже замена на Typography

2024-03-15 09:22 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        />
Отсутствует placeholder, перепроверь стили active, focus, другие

2024-03-15 09:22 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        {type === 'password' && !show && <EyeOff disabled={disabled} />}
Думаю, Eye и EyeOff стоит объединить в один компонент и управлять им через variant

2024-03-15 21:58 UTC, EvgenyStrunevsky commented on src/assets/icons/Search/index.ts
> +export * from './Search';
Почему?)

2024-03-15 21:59 UTC, EvgenyStrunevsky commented on src/assets/icons/Search/search-outline.svg
Оставил на всякий случай) Удалю)

2024-03-15 21:59 UTC, EvgenyStrunevsky commented on src/components/ui/Input/index.ts
Почему?

2024-03-15 22:00 UTC, EvgenyStrunevsky commented on src/assets/icons/Search/Search.module.scss
> +  // margin: 10px;
На нет и спроса нет)

2024-03-15 22:01 UTC, EvgenyStrunevsky commented on src/assets/icons/EyeOff/index.ts
> +export * from './EyeOff';
Почему?

2024-03-15 22:01 UTC, EvgenyStrunevsky commented on src/assets/icons/EyeOff/eye-off-outline.svg
Оставил на всякий случай) Удалю)

2024-03-15 22:02 UTC, EvgenyStrunevsky commented on src/assets/icons/EyeOff/EyeOff.tsx
> +      className={clsx(s.eye, disabled && s.disabled)}
Поддерживаю

2024-03-15 22:03 UTC, EvgenyStrunevsky commented on src/assets/icons/CloseOutline/CloseOutline.tsx
> +type Props = OwnProps & Omit<SVGProps<SVGSVGElement>, keyof OwnProps>;
Объединил и удалил Omit). Андрей Задорожный объяснил почему он здесь не нужен.

2024-03-15 22:04 UTC, EvgenyStrunevsky commented on src/assets/icons/CloseOutline/CloseOutline.tsx
> +    </svg>
Синдром накопительства) Других объяснений я не нахожу))) Удалил)

2024-03-15 22:05 UTC, EvgenyStrunevsky commented on src/assets/icons/CloseOutline/CloseOutline.tsx
> +export const CloseOutline = ({ disabled, ...otherProps }: Props) => {
Вынес)

2024-03-15 22:07 UTC, EvgenyStrunevsky commented on src/assets/icons/CloseOutline/index.ts
> +export * from './CloseOutline';
Хочу обсудить это на созвоне. Пока оставлю)

2024-03-15 22:07 UTC, EvgenyStrunevsky commented on src/assets/icons/Eye/Eye.tsx
+

2024-03-15 22:08 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +        </label>
label?

2024-03-15 22:17 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +        />
+

2024-03-15 22:18 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +        {type === 'password' && !show && <EyeOff disabled={disabled} />}
Отличный совет) Уже сделал

2024-03-19 09:55 UTC, AlexNemtsev requested changes

2024-03-19 09:55 UTC, AlexNemtsev commented on src/App.tsx
Откатить изменения в этом файле

2024-03-19 09:55 UTC, AlexNemtsev commented on src/assets/icons/Close/index.ts
> +export * from './Close';
{ Close }

2024-03-19 09:55 UTC, AlexNemtsev commented on src/assets/icons/Search/Search.module.scss
> +    fill: var(--color-dark-100);
А почему нельзя inherit сделать, как обсуждали?

2024-03-19 09:55 UTC, AlexNemtsev commented on src/assets/icons/Search/Search.module.scss
> +  &_error {
Что означает _ ?

2024-03-19 09:55 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  const cl = {
Что такое cl?

2024-03-19 09:55 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  const [inputValue, setSearchValue] = useState('');
state выпилить

2024-03-19 09:55 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  typeInput?: string;
Ограничь конкретными значениями

2024-03-19 09:55 UTC, AlexNemtsev commented on src/components/ui/Input/Input.stories.ts
> +  title: 'Components/ui/Input',
ui убрать

2024-03-21 07:39 UTC, AlexNemtsev requested changes

2024-03-21 07:39 UTC, AlexNemtsev commented on src/components/ui/Input/Input.module.scss
> +      outline: 1px solid var(--color-danger-300);
Дублирование кода, про которое мы с тобой говорили

2024-03-21 07:39 UTC, AlexNemtsev commented on src/components/ui/Input/Input.module.scss
> +  }
Дублирование кода

2024-03-21 07:39 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +} & InputHTMLAttributes<HTMLInputElement>;
Верни в типизацию type?: 'password' | 'search';

2024-03-21 07:39 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        {typePassword && <Eye disabled={disabled} show={show} />}
Поскольку prop show имеет тип boolean, то его можно писать как в html – просто show, но поскольку у тебя show никак не изменяется – константа, то из интерфейса компонента его следует убрать.

2024-03-21 15:05 UTC, AlexNemtsev requested changes

2024-03-21 15:05 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  labelValue?: string | undefined;
undefined убрать

2024-03-21 15:05 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  const classnames = {
classNames

2024-03-21 16:04 UTC, AlexNemtsev approved these changes

2024-03-22 07:48 UTC, merged