Feature/14 add dropdown component
AlexNemtsev/it-cards pull request #30
Opened 2024-03-15 19:02 UTC by mabar84

Думаю, на созвоне имелось в виду, что в качестве кнопок надо использовать уже имеющуюся компоненту  <Button>. Но есть у меня непонимание: там в пропсах моя кнопка ждет, например, 'Secondary', если не приходит, то будет "Primary' по умолчанию. Ну и т.д. Т.е. использование нашей <Button> несопоставимо сложнее, чем просто тег <button>. Всегда считал, что кастомные компоненты нужны для упрощения, а не для усложнения. Поэтому пока пушу так. Если такой подход совсем неправильный, тогда уж буду танцевать с бубном.

2024-03-18 07:38 UTC, EvgenyStrunevsky commented on src/components/ui/Dropdown/Dropdown.tsx
> +    IconButton: clsx(s.IconButton, className),
Почему здесь PascalCase?

2024-03-18 11:34 UTC, EvgenyStrunevsky requested changes

2024-03-19 08:20 UTC, AlexNemtsev requested changes

2024-03-19 08:20 UTC, AlexNemtsev commented on src/components/ui/Dropdown/Dropdown.stories.tsx
> +};
Та же история, что и с радио группой, только тут я бы сделал чуть по другому: передавать во внутрь иконку для триггера и массив с компонентами для отображения

2024-03-19 17:35 UTC, mabar84 commented on src/components/ui/Dropdown/Dropdown.tsx
> +    IconButton: clsx(s.IconButton, className),
здесь и далее отверблюдил

2024-03-19 17:55 UTC, mabar84 commented on src/components/ui/Dropdown/Dropdown.stories.tsx
> +};
Вот тут не уверен, что понял правильно. Как я это понял: пример пропсов для ДропдаунМеню:
{
icon: <Burger />,
components: [
<DropdownItem>
          <Learn />
          <Typography.Caption>Learn</Typography.Caption>
        </DropdownItem>,

<DropdownItemDivider />,

        <DropdownItem>
          <Edit />
          <Typography.Caption>Edit</Typography.Caption>
        </DropdownItem>,

        <DropdownItemDivider />,

        <DropdownItem>
          <Delete />
          <Typography.Caption>Delete</Typography.Caption>
        </DropdownItem>
]
} 
?

У нас же эти пункты меню отрисовываются на UI, их на бэке нет. Иконки тоже в компонентах захардкожены. За счет разделителей пунктов меню элементы массива неоднородные. Нужно доп. разъяснение

2024-03-20 11:39 UTC, AlexNemtsev approved these changes

2024-03-20 11:48 UTC, merged