Feature/15 add radiogroup component
AlexNemtsev/it-cards pull request #31
Opened 2024-03-18 13:51 UTC by mabar84

прошу посмотреть

2024-03-19 08:00 UTC, AlexNemtsev requested changes

2024-03-19 12:07 UTC, mabar84 commented on src/components/ui/Radiogroup/RadioGroup.stories.tsx
> +        <RadioGroupItem id="5" label="React" value="5" />
Исправлено так: в сторис 
args: {
    options: [
      { label: 'HTML', value: '1' },
      { label: 'CSS', value: '2' },
      { label: 'JS', value: '3' },
      { disabled: true, label: 'PHP disabled', value: '4' },
      { label: 'React', value: '5' },
    ],
  },
по onChange пока есть недопонимание. этот колбэк будет в ...restProps ?

2024-03-19 13:54 UTC, mabar84 commented on src/components/ui/Radiogroup/RadiogroupItem/RadioGroupItem.tsx
> +    body2: clsx(s.body2, { [s.disabled]: disabled }),
Убрал. Добавлял этот класс в том числе чтобы показать явно, что надпись может быть задизейблена. Но, наверное, это лишнее. Вполне понятно, если класс disable есть у обертки label.
 Кстати, про обнуление margin. Слазил в компоненту Типографика. Обнуляются марджины для каждого класса. Может проще было бы в styles\boylerplate.scss для p и h1-h6 обнулить? просто похоже, что прописывая reset стилей про это забыли

2024-03-19 13:56 UTC, mabar84 commented on src/components/ui/Radiogroup/RadiogroupItem/RadioGroupItem.tsx
> +    <label className={classNames.label} htmlFor={id} key={id}>
id убрал. сразу не сообразил, что для key отлично подходит value

2024-03-19 13:58 UTC, mabar84 commented on src/components/ui/Radiogroup/RadioGroup.tsx
> +} & ComponentPropsWithoutRef<typeof Root>;
Исправлено. При этом type Story = StoryObj<typeof meta> заменил на type Story = StoryObj<typeof RadioGroup>.
Тайпскрипт стал подсказывать, какие пропсы ждет история.

2024-03-20 07:59 UTC, AlexNemtsev approved these changes

2024-03-20 08:00 UTC, AlexNemtsev commented on src/components/ui/Radiogroup/RadiogroupItem/RadioGroupItem.tsx
> +    body2: clsx(s.body2, { [s.disabled]: disabled }),
Можно было бы, но думаю, фиг с ними

2024-03-20 08:00 UTC, merged