Feature/17 add select component
AlexNemtsev/it-cards pull request #32
Opened 2024-03-22 09:14 UTC by EvgenyStrunevsky

2024-03-22 10:58 UTC, AlexNemtsev requested changes

2024-03-22 10:58 UTC, AlexNemtsev commented on src/App.tsx
Файл откатить

2024-03-22 10:58 UTC, AlexNemtsev commented on src/assets/icons/ChevronUpIcon/Vector.svg
Файл удалить

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/PrimitiveSelect.module.scss
> +  &Disabled {
&.disabled

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/PrimitiveSelect.stories.tsx
> +  // title: 'Components/PrimitiveSelect',
title вернуть

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/PrimitiveSelect.tsx
> +);
Вынести в отдельный файл

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/PrimitiveSelect.tsx
> +type PropsSelectItem = {} & ComponentPropsWithoutRef<typeof Item>;
А зачем пустой объект?

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/PrimitiveSelect.tsx
> +export const PrimitiveSelect = (props: Props) => {
переименовать в Select

2024-03-22 10:58 UTC, AlexNemtsev commented on src/components/ui/Select/Types.ts
Переименовать файл в соответствии с названием типа

2024-03-22 11:14 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Types.ts
SelectType.ts?

2024-03-22 11:15 UTC, EvgenyStrunevsky commented on src/components/ui/Select/PrimitiveSelect.tsx
> +type PropsSelectItem = {} & ComponentPropsWithoutRef<typeof Item>;
Трудно сказать) Поправлю)

2024-03-22 11:18 UTC, EvgenyStrunevsky commented on src/components/ui/Select/PrimitiveSelect.module.scss
> +  &Disabled {
А как его прописать в clsx()?

2024-03-22 14:21 UTC, AlexNemtsev requested changes

2024-03-22 14:21 UTC, AlexNemtsev commented on src/components/ui/Select/Select.stories.tsx
> +  title: 'Components/PrimitiveSelect',
Убрать Primitive

2024-03-22 14:21 UTC, AlexNemtsev commented on src/components/ui/Select/Select.tsx
> +  };
Объект не нужен

2024-03-22 14:21 UTC, AlexNemtsev commented on src/components/ui/Select/SelectItem/SelectItem.tsx
> +  ({ children, className, ...props }: Props, forwardedRef: ForwardedRef<HTMLDivElement>) => {
forwardRef((props: Props, forwardedRef: ForwardedRef<HTMLDivElement>) => {
 const { children, className, ...rest } = props;

2024-03-23 10:17 UTC, mabar84 requested changes
Выбрал Request changes, т.е. одна правка и можно мержить

2024-03-23 10:17 UTC, mabar84 commented on src/components/ui/Select/Select.tsx
> +  };
Саша в комментарии про "объект не нужен", видимо, имел в виду, это
1)   const label = clsx(s.label, { [s.disabled]: disabled }, className);
или это
2)  const label = clsx(s.label, disabled && s.disabled, className);

Идея такая, что для одного класса создавать объект смысла нет. Но в данной компоненте много классов используется. У того же инкубатора если в компоненте много тегов с классами, то у того же инкубатора создается объект со всеми классами данной компоненты. Т.е. либо собрать все в большой объект, либо имеющийся объект заменить просто строкой.

2024-03-23 13:02 UTC, AlexNemtsev commented on src/components/ui/Select/Select.tsx
> +  };
Всё так, заменить строкой

2024-03-23 17:44 UTC, AlexNemtsev approved these changes

2024-03-23 17:45 UTC, merged