fix/17_add_select_component-controllability
AlexNemtsev/it-cards pull request #33
Opened 2024-03-25 16:09 UTC by EvgenyStrunevsky

Добавил возможность подстроить компонент Select под пагинацию, сделал его управляемым.

2024-03-26 07:43 UTC, AlexNemtsev requested changes

2024-03-26 07:43 UTC, AlexNemtsev commented on src/components/ui/Select/Select.module.scss
> +  line-height: var(--line-height-m);
Если ты настраиваешь размеры текста, то скорее всего тебе нужен компонент типографики

2024-03-26 07:43 UTC, AlexNemtsev commented on src/components/ui/Select/Select.module.scss
> +    line-height: var(--line-height-m);
типографика

2024-03-26 07:43 UTC, AlexNemtsev commented on src/components/ui/Select/SelectItem/SelectItem.module.scss
>    line-height: 1;
Типографика

2024-03-26 07:43 UTC, AlexNemtsev commented on src/components/ui/Select/Select.tsx
> +  labelValue?: number | string;
label

2024-03-26 07:43 UTC, AlexNemtsev commented on src/components/ui/Select/Select.tsx
> +  placeholder: number | string;
а number тут для чего?

2024-03-26 09:47 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.tsx
> +  placeholder: number | string;
Уже не нужен)

2024-03-26 09:48 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.tsx
> +  labelValue?: number | string;
+

2024-03-26 15:05 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.module.scss
> +  line-height: var(--line-height-m);
+

2024-03-26 15:51 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.module.scss
> +    line-height: var(--line-height-m);
+

2024-03-26 15:51 UTC, EvgenyStrunevsky commented on src/components/ui/Select/SelectItem/SelectItem.module.scss
>    line-height: 1;
+

2024-03-27 19:32 UTC, mabar84 requested changes
Нашел только, что в App.tsx удалено слово hello. 
Выбрал Submit feedback that must be addressed before merging.
Но напомню, что не в курсе многих моментов, которые обсуждались без меня

2024-03-28 04:49 UTC, AlexNemtsev requested changes

2024-03-28 04:49 UTC, AlexNemtsev commented on src/components/ui/Select/Select.stories.tsx
> +};
Не тот случай, когда нужно использовать as – скорее всего тебе нужно вывести тип props твоего компонента

2024-03-28 04:49 UTC, AlexNemtsev commented on src/components/ui/Select/Select.stories.tsx
> +  render: () => {
Содержимое объекта args нужно передавать в функцию render https://storybook.js.org/docs/api/csf

2024-03-28 04:49 UTC, AlexNemtsev commented on src/components/ui/Select/Select.tsx
> +                  <SelectItem isSmall={!!isSmall} key={item.id} value={item.value}>
Зачем "!!" ? isSmall и так имеет тип boolean

2024-03-28 04:49 UTC, AlexNemtsev commented on src/components/ui/Select/SelectItem/SelectItem.module.scss
>    line-height: 1;
line-height тут зачем?

2024-03-28 05:11 UTC, AlexNemtsev requested changes

2024-03-28 05:11 UTC, AlexNemtsev commented on src/components/ui/Select/SelectItem/TypographySelector/TypographySelector.tsx
Вынеси на уровень выше

2024-03-28 21:49 UTC, EvgenyStrunevsky commented on src/App.tsx
> +  return <div></div>;
+

2024-03-28 21:58 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.stories.tsx
> +};
+

2024-03-28 21:58 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.stories.tsx
> +  render: () => {
+

2024-03-28 21:59 UTC, EvgenyStrunevsky commented on src/components/ui/Select/Select.tsx
> +                  <SelectItem isSmall={!!isSmall} key={item.id} value={item.value}>
+

2024-03-28 22:15 UTC, EvgenyStrunevsky commented on src/components/ui/Select/SelectItem/SelectItem.module.scss
>    line-height: 1;
+

2024-03-28 22:17 UTC, EvgenyStrunevsky commented on src/components/ui/Select/SelectItem/TypographySelector/TypographySelector.tsx
+

2024-04-01 07:16 UTC, AlexNemtsev approved these changes

2024-04-01 07:19 UTC, merged