fix/8_add_select_component-controllability
AlexNemtsev/it-cards pull request #34
Opened 2024-03-25 20:55 UTC by EvgenyStrunevsky

Сделал компонент Input управляемым.

2024-03-26 07:36 UTC, AlexNemtsev requested changes

2024-03-26 07:36 UTC, AlexNemtsev commented on src/assets/icons/Eye/Eye.tsx
> +  const { disabled, maskedPassword, show, showPassword, ...otherProps } = props;
otherProps –> restProps

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  clearSearch?: () => void;
clearInput

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
>    labelValue?: string;
label

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  showPassword?: (value: boolean) => void;
Состояние скрыт пароль или нет должно быть внутри инпута

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        {typeSearch && value && <Close handleClickClose={clearSearch!} isError={!!error} />}
Наверное, есть резон переименовать иконку с Close на Cross

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        {typeSearch && value && <Close handleClickClose={clearSearch!} isError={!!error} />}
Плюс вынеси логику из Close и Eye – это должны быть "тупые" компоненты, которые лежит внутри компонентов с логикой

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
>    typeValue?: 'password' | 'search';
type

2024-03-26 07:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +  showPassword?: (value: boolean) => void;
Сделай state на тип password/text, инициализироваться он должен из props, а управляться кнопкой с иконкой глаза

2024-03-26 07:51 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +  clearSearch?: () => void;
+

2024-03-26 07:52 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
>    labelValue?: string;
labelValue изменить на label?

2024-03-26 08:08 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +  showPassword?: (value: boolean) => void;
+

2024-03-26 08:50 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
>    labelValue?: string;
+

2024-03-26 08:52 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +        {typeSearch && value && <Close handleClickClose={clearSearch!} isError={!!error} />}
+

2024-03-26 08:52 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
>    typeValue?: 'password' | 'search';
+

2024-03-28 04:36 UTC, AlexNemtsev requested changes

2024-03-28 04:36 UTC, AlexNemtsev commented on src/App.tsx
Откатить

2024-03-28 04:36 UTC, AlexNemtsev commented on src/assets/icons/Eye/Eye.tsx
Eye не должен содержать в себе логику – только отрисовка иконки

2024-03-28 04:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +      <div className={clsx(s.field, disabled && s.disabled)}>
Вынеси стили

2024-03-28 04:36 UTC, AlexNemtsev commented on src/assets/icons/Cross/Cross.tsx
> +} & SVGProps<SVGSVGElement>;
Убрать, иконка не должна знать о том, isError она или нет. Используй className для стилизации. Вспомни путь самурая – презентационный компонент должен быть максимально тупым, вся логика должна лежать выше

2024-03-28 04:36 UTC, AlexNemtsev commented on src/components/ui/Input/Input.tsx
> +        {typeSearch && value && <Cross isError={!!error} onClick={clearInput} />}
Вместо isError применяй className как и в типографике

2024-03-28 06:54 UTC, EvgenyStrunevsky commented on src/App.tsx
+

2024-03-28 07:18 UTC, EvgenyStrunevsky commented on src/components/ui/Input/Input.tsx
> +      <div className={clsx(s.field, disabled && s.disabled)}>
+

2024-03-28 09:51 UTC, EvgenyStrunevsky commented on src/assets/icons/Eye/Eye.tsx
+

2024-03-28 21:27 UTC, EvgenyStrunevsky commented on src/assets/icons/Cross/Cross.tsx
> +} & SVGProps<SVGSVGElement>;
+

2024-04-01 07:11 UTC, AlexNemtsev approved these changes

2024-04-01 07:11 UTC, AlexNemtsev commented on src/assets/icons/EyeOff/EyeOff.tsx
> +  const { ...restProps } = props;
Деструктуризация тут ненужна

2024-04-01 07:11 UTC, AlexNemtsev commented on src/assets/icons/Search/Search.tsx
> +  const { ...otherProps } = props;
Тоже избыточно

2024-04-01 07:29 UTC, EvgenyStrunevsky commented on src/assets/icons/Search/Search.tsx
> +  const { ...otherProps } = props;
+

2024-04-01 08:55 UTC, merged