13 add pagination component
AlexNemtsev/it-cards pull request #42
Opened 2024-03-27 21:14 UTC by mabar84

Как ревьюить без сторибука? Совершенно не понимаю. Это компилятор в голове надо иметь. Т.к. сторибук я не задеплоил, то на созвоне пошарю экран

2024-03-28 05:09 UTC, AlexNemtsev requested changes

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/PagintionButtons/ArrowButton/ArrowButton.tsx
> +      </svg>
Вынеси в assets

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/Pagination.tsx
> +      {/*/>*/}
Удалить

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/PagintionButtons/index.ts
> +export { PagintionButtons } from './PagintionButtons';
Добавь в этот импорт ArrowButtons

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/Pagination.tsx
> +import { PagintionButtons } from '@/components/ui/Pagination/PagintionButtons/PagintionButtons';
Будет лучше сократить пути импортов ./PaginationButtons

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/Pagination.tsx
> +} & ComponentPropsWithoutRef<'div'>;
Зачем props от div?

2024-03-28 05:09 UTC, AlexNemtsev commented on src/components/ui/Pagination/Pagination.tsx
> +  };
Заведи state

2024-03-28 10:06 UTC, mabar84 commented on src/components/ui/Pagination/PagintionButtons/index.ts
> +export { PagintionButtons } from './PagintionButtons';
Тут не понял, ArrowButton - это папка в папке PagintionButtons. А в ArrowButton есть ArrowButton.tsx 
Оттуда export { ArrowButton } from './ArrowButton';

2024-04-01 07:14 UTC, AlexNemtsev approved these changes

2024-04-01 07:15 UTC, merged