Feature/16 add modal component
AlexNemtsev/it-cards pull request #45
Opened 2024-04-02 08:44 UTC by EvgenyStrunevsky

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.tsx
> +        </Button>
по макету тут Subtitle2

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.tsx
> +import { Typography } from '../Typography';
заматерел, расслабился :) импорты можно сделать посимпатичнее

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.module.scss
> +}
на уроке Андрей говорит, что это потенциально утечка стилей. потестил, не смог добиться утечки. поэтому можно оставить, но запомнить. если с кнопками в проекте будет что-то происходить, будем смотреть в сторону модалки

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.module.scss
> +
при адаптиве тут проблемы. но можно пропустить, т.к. нормального адаптива для модалки не отрисовано. когда соберем проект, будем адаптив допиливать. с кнопками в футере модалки та же история

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.stories.tsx
> +      </div>
это children, их пишем в строке 43
  render: ({ children, title }) => {

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.stories.tsx
> +          </div>
заменяем на {children}

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/Modal.stories.tsx
> +        <ModalButton type="reset" variant="secondary">
не люблю инлайновые стили. но если уж пишешь, то добавь gap: '20px'

2024-04-03 19:53 UTC, mabar84 commented on src/components/ui/Modal/ModalButton/ModalButton.tsx
> +import { Typography } from '../../Typography';
импорты

2024-04-04 08:45 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.tsx
> +        </Button>
+

2024-04-04 08:45 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.tsx
> +import { Typography } from '../Typography';
+

2024-04-04 08:50 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.module.scss
> +}
+

2024-04-04 08:58 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.module.scss
> +
width: 50%;
  min-width: 300px; 
  Сделал пока так

2024-04-04 09:03 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.stories.tsx
> +      </div>
А как тогда повесить на ModalButton обработчики addNewCard и resetForm, если они созданы в render?

2024-04-04 09:04 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/Modal.stories.tsx
> +        <ModalButton type="reset" variant="secondary">
Как здесь может быть альтернатива инлайну?

2024-04-04 09:05 UTC, EvgenyStrunevsky commented on src/components/ui/Modal/ModalButton/ModalButton.tsx
> +import { Typography } from '../../Typography';
+

2024-04-05 11:42 UTC, mabar84 requested changes
осталось по версии сторибука определиться

2024-04-05 11:42 UTC, mabar84 commented on package.json
> +    "@storybook/test": "^8.0.5",
либо возвращаем тут 7-ю, либо все в понедельник обсуждаем и если ок, то переходим на 8-ю.

2024-04-09 13:39 UTC, AlexNemtsev approved these changes

2024-04-09 16:27 UTC, AlexNemtsev approved these changes

2024-04-09 16:27 UTC, merged