Feature/51 add sign up form component
AlexNemtsev/it-cards pull request #63
Opened 2024-04-15 20:44 UTC by EvgenyStrunevsky

Есть несколько сырых мест)

2024-04-17 07:31 UTC, AlexNemtsev commented on src/components/auth/LogUp/LogUp.module.scss
> +  max-width: 420px;
Заменить на миксин

2024-04-17 11:54 UTC, EvgenyStrunevsky commented on src/components/auth/LogUp/LogUp.module.scss
> +  max-width: 420px;
+

2024-04-17 12:16 UTC, mabar84 requested changes

2024-04-17 12:16 UTC, mabar84 commented on src/components/auth/LogUpForm/LogUpForm.module.scss
> +
в середине 2 слеша
ну и @import '@/styles/form-container-mixin.scss'; красивее

2024-04-17 12:16 UTC, mabar84 commented on src/components/auth/LogUpForm/LogUpForm.module.scss
> +  margin: 0 auto;
есть в миксине

2024-04-17 12:16 UTC, mabar84 commented on src/components/auth/LogUpForm/LogUpForm.stories.tsx
> +import { LogUpForm } from '.';
5 строка - не понятно

2024-04-17 12:16 UTC, mabar84 commented on src/components/withControllers/InputWithController/InputWithController.tsx
> +    name: props.name,
вроде переделывалось уже на control и name просто

2024-04-17 12:16 UTC, mabar84 commented on src/components/withControllers/InputWithController/InputWithController.tsx
> +  return <Input {...props} {...field} error={error?.message} />;
может так
export const InputWithController = <T extends FieldValues>(props: Props<T>) => {
  const { control, name, ...rest } = props;
  const {
    field: { value, ...restField },
    fieldState: { error },
  } = useController({
    control,
    name,
  });

  return <Input {...rest} error={error?.message} {...restField} name={name} />;
};

2024-04-17 12:16 UTC, mabar84 commented on src/components/withControllers/InputWithController/InputWithController.tsx
> +  return <Input {...props} {...field} error={error?.message} />;
Только надо выбрать ...rest, ...props или ...restProps

2024-04-17 12:16 UTC, mabar84 commented on package.json
> +    "react-hook-form": "^7.51.2",
откатили версию?

2024-04-17 12:16 UTC, mabar84 commented on src/components/withControllers/InputWithController/InputWithController.tsx
> +export type ControlledTextFieldProps<T extends FieldValues> = {
не писал бы, но все равно еще другие правки есть:
 Вместо ControlledTextFieldProps просится  ControlledInputProps

2024-04-17 12:22 UTC, EvgenyStrunevsky commented on src/components/withControllers/InputWithController/InputWithController.tsx
> +  return <Input {...props} {...field} error={error?.message} />;
блин... у меня изменения куда-то испарились. Сейчас передела

2024-04-17 12:41 UTC, EvgenyStrunevsky commented on src/components/auth/LogUpForm/LogUpForm.module.scss
> +
+

2024-04-17 12:41 UTC, EvgenyStrunevsky commented on src/components/auth/LogUpForm/LogUpForm.module.scss
> +  margin: 0 auto;
+

2024-04-17 12:42 UTC, EvgenyStrunevsky commented on src/components/auth/LogUpForm/LogUpForm.stories.tsx
> +import { LogUpForm } from '.';
vscode предложил такой импорт, он работает) Поэтому он здесь)

2024-04-18 18:14 UTC, mabar84 requested changes

2024-04-18 18:14 UTC, mabar84 commented on package.json
> +    "react-hook-form": "^7.51.2",
сейчас в develop 7.51.3       кто знает, может быть покраснение консоли при работе с реакт-хук-форм зависит от версии.   ну и просто должна быть та версия, которая в ветке develop

2024-04-18 18:14 UTC, mabar84 commented on src/App.tsx
> +  return <div>] hello</div>;
<div>hello</div>

2024-04-19 10:15 UTC, EvgenyStrunevsky commented on package.json
> +    "react-hook-form": "^7.51.2",
+

2024-04-19 10:15 UTC, EvgenyStrunevsky commented on src/App.tsx
> +  return <div>] hello</div>;
+

2024-04-19 10:15 UTC, EvgenyStrunevsky commented on src/App.tsx
+

2024-04-19 10:15 UTC, EvgenyStrunevsky commented on src/components/auth/LogUpForm/LogUpFormShema.ts
> +    password: z.string().min(3),
+

2024-04-19 11:27 UTC, AlexNemtsev approved these changes

2024-04-19 11:28 UTC, merged