Feature/54 personal information
AlexNemtsev/it-cards pull request #73
Opened 2024-04-22 22:07 UTC by mabar84

Что хотелось бы доработать с вашей помощью:
1) у Валеры стащил решение по инпуту для подгрузки картинки. Там  внутри span, а не button. Иначе не работает. Минусы - не работает переключение по Tab. Решается tabindex={}. Но тогда пробел или ввод не отрабатывают. Костыли с onClick и рефами не хочется. Будут мысли - велкам
2) чтобы при клике на "Редактировать имя" в инпуте было не пусто, а подгрузилось редактируемое имя

2024-04-23 12:37 UTC, EvgenyStrunevsky reviewed
components/profile/PersonalInformation

2024-04-23 13:10 UTC, EvgenyStrunevsky commented on src/components/auth/PersonalInformation/PersonalInformation.tsx
> +        </form>
Форму с валидацией стоит вынести в отдельный компонент

2024-04-24 09:43 UTC, mabar84 commented on src/components/auth/PersonalInformation/PersonalInformation.tsx
> +          </Button>
+

2024-04-24 09:55 UTC, mabar84 commented on src/components/auth/PersonalInformation/PersonalInformation.tsx
> +        </form>
+

2024-04-24 11:17 UTC, AlexNemtsev requested changes

2024-04-24 11:17 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.stories.tsx
> +  },
Нужно вынести в отдельный компонент

2024-04-24 11:17 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.stories.tsx
> +    const [nickname, setName] = useState(name);
avatar, setAvatar

2024-04-24 19:03 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +
Андрей говорит, что не стоит писать стили по селектору тега.

2024-04-24 19:07 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +        <img alt="avatar" className={s.avatar} src={avatar} />
Аватар есть в двух местах макета, напрашивается отдельный компонент.

2024-04-24 19:22 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +  }
Эти стили относятся к Typography.H1? Компонент Typography принимает  стили через className

2024-04-24 19:43 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +        box-shadow: 0 2px 10px 0 #6d6d6d40;
Цвет в переменную

2024-04-24 19:43 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +      fill: currentcolor;
Возможно атрибут fill со значением currentcolor можно оставить в самой иконке, но не уверен.

2024-04-24 20:14 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +      reader.readAsDataURL(e.target.files[0]);
Можно проверить размер загружаемого файла.
Например: if (e.target.files[0].size > 300 * 1024) {
alert('Слишком большой файл')
}

2024-04-24 20:20 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +  setAvatar: (file: any) => void;
any

2024-04-24 21:27 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +        <img alt="avatar" className={s.avatar} src={avatar} />
а где еще? нашел в Header, так там размер картинки маленький. допускаю, что даже отдельным файлом изображение хранится

2024-04-24 21:29 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +        </label>
<input htmlFor='file'  - тут, видимо, id. Иначе ругается

2024-04-24 21:52 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +        box-shadow: 0 2px 10px 0 #6d6d6d40;
видел этот момент. нет в наборе такой переменной. лезть руками в общий файл стилей не решился. посчитал, что эта тень при любых изменениях дизайна так и останется легким туманом

2024-04-24 21:53 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +      fill: currentcolor;
скорее всего. даже залез в эту компоненту сразу. а потом подумал, что она используется где-то еще. и решил, что лучше стилями обойдусь

2024-04-24 21:55 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +      reader.readAsDataURL(e.target.files[0]);
это да. только тут имитация в сторибуке. давай дождемся работы с сервером. я даже не знаю еще, будем ли работать прямо так, без преобразований в Blob и т.п.

2024-04-24 21:56 UTC, mabar84 commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +  setAvatar: (file: any) => void;
+

2024-04-24 22:04 UTC, mabar84 commented on src/components/profile/PersonalInformation/EditNickNameForm.tsx
> +export const EditNickNameForm = ({ onSubmit }: Props) => {
я все же оставил бы так. общий размер форматированного файла - 40 строк. при свернутых инпутах чуть больше половины экрана.   про файл с валидацией - для меня осталось не понятным, речь про много маленьких файлов по паре строк или про один файл с валидацией для 5 форм? на одном из созвонов было решено, что когда накидаем карточек по 3-му уроку, тогда при необходимости вынесем в отдельную таску этот вопрос с валидациями

2024-04-25 09:09 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +        </label>
`.button {
  position: relative;
}

.input {
  position: absolute;
  z-index: -10;
  display: block;
  width: 0;
  height: 0;
  opacity: 0;
  &:focus + .file {
    border: 1px solid white;
  }
}

.file {
  cursor: pointer;
  padding: 5px 10px;
  background-color: rgb(27, 62, 158);
}
/////////////
      <label className={s.button}>
        <input className={s.input} onChange={uploadHandler} type="file" />
        <span className={s.file}>File</span>
      </label>
`
Так все работает. Проверил. Пробуй.

2024-04-25 10:27 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/EditNickNameForm.tsx
> +export const EditNickNameForm = ({ onSubmit }: Props) => {
Здесь речь не о количестве строк, а разделении логики и представления.

2024-04-25 10:27 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +      reader.readAsDataURL(e.target.files[0]);
+

2024-04-25 10:33 UTC, EvgenyStrunevsky commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +        box-shadow: 0 2px 10px 0 #6d6d6d40;
Создай переменную, это хорошая практика.

2024-04-25 11:33 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +}
Поддерживаю

2024-04-25 11:41 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.tsx
> +        <img alt="avatar" className={s.avatar} src={avatar} />
Лучше вынести

2024-04-26 11:45 UTC, AlexNemtsev approved these changes

2024-04-26 11:59 UTC, AlexNemtsev requested changes

2024-04-26 11:59 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/EditNickNameForm/EditNickNameForm.tsx
> +import s from '@/components/profile/PersonalInformation/PersonalInformation.module.scss';
from './'

2024-04-26 11:59 UTC, AlexNemtsev commented on src/components/profile/PersonalInformation/PersonalInformation.module.scss
> +}
убрать

2024-04-26 16:42 UTC, AlexNemtsev approved these changes

2024-04-26 16:42 UTC, merged