Feature/52 forgot password
AlexNemtsev/it-cards pull request #74
Opened 2024-04-23 10:29 UTC by mabar84

ForgotPassword разбил на три компоненты по примеру одного знаменитого самурая
https://github.com/Dotroga/Cards-new/tree/master/src/components/auth

2024-04-24 11:11 UTC, AlexNemtsev requested changes

2024-04-24 11:11 UTC, AlexNemtsev commented on src/components/auth/CheckEmail/CheckEmail.stories.tsx
> +  },
рендер функция избыточна

2024-04-24 11:11 UTC, AlexNemtsev commented on src/components/auth/CheckEmail/CheckEmail.tsx
> +  onClick: () => void;
Нужно конкретизировать, что за onClick у формы

2024-04-24 11:11 UTC, AlexNemtsev commented on src/components/auth/CreateNewPassword/CreateNewPassword.stories.tsx
> +  },
убрать

2024-04-24 11:11 UTC, AlexNemtsev commented on src/components/auth/ForgotPassword/ForgotPassword.stories.tsx
> +  },
убрать

2024-04-26 07:42 UTC, AlexNemtsev commented on src/components/auth/CheckEmail/CheckEmail.module.scss
> +  }
Эти стили нужно задать типографике

2024-04-26 07:43 UTC, AlexNemtsev commented on src/components/auth/CheckEmail/CheckEmail.stories.tsx
> +      console.log('Back to Sign In');
Замени на action

2024-04-26 07:44 UTC, AlexNemtsev commented on src/components/auth/CreateNewPassword/CreateNewPassword.stories.tsx
> +      console.log(data.password);
Тоже замени на action

2024-04-26 07:44 UTC, AlexNemtsev commented on src/components/auth/ForgotPassword/ForgotPassword.stories.tsx
> +      console.log(data.email);
action

2024-04-26 10:07 UTC, EvgenyStrunevsky commented on src/components/auth/ForgotPassword/ForgotPassword.tsx
> +      <Typography.H1>Forgot your password?</Typography.H1>
Если в handleSubmit обернуть иницализацию функции onSubmitHandler, типизация аргумента data отпадает. А в onSubmit сразу передаем onSubmitHandler. Рекомендация Андрея.

2024-04-26 10:21 UTC, EvgenyStrunevsky commented on src/components/auth/ForgotPassword/ForgotPassword.module.scss
> +}
Для себя. А почему не так?
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 7px;
  white-space: nowrap;

2024-04-26 10:33 UTC, mabar84 commented on src/components/auth/ForgotPassword/ForgotPassword.module.scss
> +  }
+

2024-04-26 10:34 UTC, mabar84 commented on src/components/auth/ForgotPassword/ForgotPassword.tsx
> +export type FormValues = z.infer<typeof forgotPasswordScheme>;
Да понял я, понял. Эту карточку с задачей по выносу логики валидации в числе карточек по 3-му уроку обязательно оставлю тебе

2024-04-26 10:36 UTC, mabar84 commented on src/components/auth/ForgotPassword/ForgotPassword.module.scss
> +}
был у меня коллега, бородатый тестер. Приучил, что ширина ссылки должна быть равна контенту. Т.е. чтобы курсор, находящийся справа от текста, не становился pointer

2024-04-26 10:49 UTC, mabar84 commented on src/components/auth/ForgotPassword/ForgotPassword.tsx
> +      <Typography.H1>Forgot your password?</Typography.H1>
что-то такое помнится. но по текстовому описанию ничего не понял. сможешь куском кода или ссылкой с меткой времени - будет супер

2024-04-26 10:56 UTC, mabar84 commented on src/components/auth/ForgotPassword/ForgotPassword.stories.tsx
> +      console.log(data.email);
+

2024-04-26 10:56 UTC, mabar84 commented on src/components/auth/CreateNewPassword/CreateNewPassword.stories.tsx
> +      console.log(data.password);
+

2024-04-26 10:57 UTC, mabar84 commented on src/components/auth/CheckEmail/CheckEmail.stories.tsx
> +      console.log('Back to Sign In');
+

2024-04-26 10:58 UTC, EvgenyStrunevsky commented on src/components/auth/ForgotPassword/ForgotPassword.tsx
> +      <Typography.H1>Forgot your password?</Typography.H1>
ок

2024-04-26 11:18 UTC, AlexNemtsev approved these changes

2024-04-26 11:25 UTC, AlexNemtsev commented on src/components/auth/ForgotPassword/ForgotPassword.tsx
> +      <Typography.H1>Forgot your password?</Typography.H1>
```js
const onSubmitHandler = handleSubmit((data) => {
    onSubmit(data);
  });
```

2024-04-26 16:41 UTC, merged