fix/95-Pagination-add-ItemsPerPage
AlexNemtsev/it-cards pull request #96
Opened 2024-05-16 19:47 UTC by EvgenyStrunevsky

2024-05-20 07:37 UTC, AlexNemtsev requested changes

2024-05-20 07:37 UTC, AlexNemtsev commented on src/shared/ui/Pagination/Pagination.tsx
> +          ]}
Вынеси в отдельную константу, плюс ещё здесь напрашивается генерация этих значений https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#using_arrow_functions_and_array.from
а id вполне может быть равен value

2024-05-20 07:37 UTC, AlexNemtsev commented on src/shared/ui/Pagination/Pagination.stories.tsx
> +    const [items, setItems] = useState(itemsPerPage);
items –> itemsPerPage

2024-05-20 07:37 UTC, AlexNemtsev commented on src/shared/ui/Pagination/Pagination.tsx
>    itemsPerPage: number;
лучше переименовать defaultItemsCountPerPage

2024-05-20 07:37 UTC, AlexNemtsev commented on src/shared/ui/Pagination/Pagination.stories.tsx
Переименуй истории: PaginationWith7Pages и PaginationWith12Pages

2024-05-20 10:47 UTC, EvgenyStrunevsky commented on src/shared/ui/Pagination/Pagination.tsx
> +          ]}
+

2024-05-22 10:46 UTC, EvgenyStrunevsky commented on src/shared/ui/Pagination/Pagination.stories.tsx
+

2024-05-22 12:02 UTC, AlexNemtsev requested changes

2024-05-22 20:03 UTC, EvgenyStrunevsky commented on src/shared/ui/Pagination/Pagination.stories.tsx
> +const VALUES: string[] = ['10', '20', '30', '50', '100'];
+

2024-05-23 09:52 UTC, AlexNemtsev requested changes

2024-05-23 09:52 UTC, AlexNemtsev commented on src/shared/ui/Pagination/Pagination.tsx
> +  values: string[];
itemsPerPageList, думаю будет нагляднее

2024-05-23 10:24 UTC, EvgenyStrunevsky commented on src/shared/ui/Pagination/Pagination.tsx
> +  values: string[];
+

2024-05-23 12:16 UTC, AlexNemtsev approved these changes

2024-05-23 12:19 UTC, merged